Initial Work Mint Button
monax/aspen-publishing-sdk pull request #1
Opened 2022-08-11 10:23 UTC by lupotto

2022-08-17 11:35 UTC, DeanVanNiekerk requested changes

2022-08-17 11:35 UTC, DeanVanNiekerk commented on pkg/examples/react/src/pages/index.tsx
> +    : "0x021aa5a885bdb6a8767e5e4909d1cf594255106a";
can we not do this?
```suggestion
  const [nftInputContractAddress, setNftInputContractAddress] = useState("0x021aa5a885bdb6a8767e5e4909d1cf594255106a");
```

2022-08-17 11:35 UTC, DeanVanNiekerk commented on pkg/examples/react/src/pages/index.tsx
> +  async function tryGetContractAgreementIPFS(
```suggestion
  async function tryGetCedarAgreementContract(
```

2022-08-17 11:35 UTC, DeanVanNiekerk commented on pkg/examples/react/src/pages/index.tsx
> +        <text>Accept Terms Contract </text>
```suggestion
        <text>Contract Address</text>
```

2022-08-17 11:35 UTC, DeanVanNiekerk commented on pkg/examples/react/src/pages/index.tsx
> +  const getContract = async () => {
```suggestion
  const onMint = async () => {
```

2022-08-17 11:35 UTC, DeanVanNiekerk commented on pkg/examples/react/src/pages/index.tsx
> +      "0xd18d8a12c868EC243Afa3371c6C98Bf8631d7246",
this should be the same address from the input

2022-08-17 11:35 UTC, DeanVanNiekerk commented on pkg/examples/react/src/pages/index.tsx
> +        <button type="button" onClick={onClick}>
```suggestion
        <button type="button" onClick={onMint}>
```

2022-08-17 11:35 UTC, DeanVanNiekerk commented on pkg/examples/react/src/pages/index.tsx
> +        <h2>Welcome to Aspen Publishing SDK </h2>
```suggestion
        <h2>Aspen Publishing SDK Example</h2>
```

2022-08-18 08:22 UTC, DeanVanNiekerk commented
Mint and AcceptTerms are still potentially using different addresses, can we do something like

```tsx
import type { NextPage } from "next";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

import { useWeb3React } from "@web3-react/core";
import { Web3Provider } from "@ethersproject/providers";
import { InjectedConnector } from "@web3-react/injected-connector";
import {
  CedarERC721DropV0__factory,
  ICedarAgreementV0,
  ICedarAgreementV0__factory,
} from "@monax/aspen-publishing-sdk";
import { Signer } from "ethers";

const ConnectWallet = () => {
  const injectedConnector = new InjectedConnector({
    supportedChainIds: [1, 3, 4, 5, 42, 80001],
  });
  const { chainId, account, activate, active, library } =
    useWeb3React<Web3Provider>();

  const onClick = () => {
    activate(injectedConnector);
  };

  useEffect(() => {
    console.log(chainId, account, active);
  });

  return (
    <div>
      <div>ChainId: {chainId}</div>
      <div>Account: {account}</div>
      {active ? (
        <div>✅ </div>
      ) : (
        <button type="button" onClick={onClick}>
          Connect
        </button>
      )}
    </div>
  );
};

const AcceptTerms: React.FC<{ contractAddress: string }> = ({
  contractAddress,
}) => {
  const { account, active, library } = useWeb3React<Web3Provider>();

  const onAcceptTerms = async () => {
    const contract = await getContractAgreement(
      contractAddress,
      library.getSigner()
    );
    try {
      await contract.termsActivated();
      await checkHasAcceptedTerms();
      await tryGetCedarAgreementContract(contractAddress, library.getSigner());

      await contract.acceptTerms();
    } catch (err) {
      console.error(err);
    }
  };

  const checkHasAcceptedTerms = async () => {
    if (!library) return;
    const erc721Cedar = await ICedarAgreementV0__factory.connect(
      contractAddress,
      library.getSigner()
    );
    return erc721Cedar.getAgreementStatus(account);
  };

  async function getContractAgreement(
    nftContractAddress: string,
    signer: Signer
  ): Promise<ICedarAgreementV0> {
    return ICedarAgreementV0__factory.connect(nftContractAddress, signer);
  }

  async function tryGetCedarAgreementContract(
    nftContractAddress: string,
    signer: Signer
  ): Promise<string | null> {
    try {
      const cedar = ICedarAgreementV0__factory.connect(
        nftContractAddress,
        signer
      );
      const agreementInIPFS = await cedar.userAgreement();
      return agreementInIPFS;
    } catch (err) {
      console.error(err);
      return null;
    }
  }

  return (
    active && (
      <button type="button" onClick={onAcceptTerms}>
        Accept Terms
      </button>
    )
  );
};

const Mint: React.FC<{ contractAddress: string }> = ({ contractAddress }) => {
  const { account, active, library } = useWeb3React<Web3Provider>();

  const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";
  const ZERO_BYTES =
    "0x0000000000000000000000000000000000000000000000000000000000000000";

  const onMint = async () => {
    if (!library) return;
    const contract = CedarERC721DropV0__factory.connect(
      contractAddress,
      library.getSigner()
    );

    const condition = {
      maxClaimableSupply: 100,
      quantityLimitPerTransaction: 100,
      startTimestamp: Math.floor(Date.now() / 1000).toString(),
      supplyClaimed: 0,
      waitTimeInSecondsBetweenClaims: 0,
      merkleRoot: ZERO_BYTES,
      pricePerToken: 0,
      currency: ZERO_ADDRESS,
    };

    await contract.setClaimConditions([condition], false, {
      gasLimit: 100000,
    });

    await contract.lazyMint(1, "", ZERO_BYTES, {
      gasLimit: 100000,
    });

    const response = await contract.claim(account, 1, ZERO_ADDRESS, 0, [], 0, {
      gasLimit: 100000,
    });
  };
  return (
    active && (
      <div>
        <button type="button" onClick={onMint}>
          Mint
        </button>
      </div>
    )
  );
};

const Home: NextPage = () => {
  const [nftInputContractAddress, setNftInputContractAddress] = useState(
    "0x021aa5a885bdb6a8767e5e4909d1cf594255106a"
  );

  return (
    <div>
      <main className={styles.main}>
        <h2>Aspen Publishing SDK Example </h2>
        <ConnectWallet />
        <div>
          <text>Contract Address </text>
          <input
            type="text"
            value={nftInputContractAddress}
            onChange={(e) => setNftInputContractAddress(e.target.value)}
          />
        </div>
        <AcceptTerms contractAddress={nftInputContractAddress} />
        <Mint contractAddress={nftInputContractAddress} />
      </main>
    </div>
  );
};

export default Home;

```

2022-08-18 11:40 UTC, danielz-mnx commented on pkg/examples/react/src/pages/index.tsx
> +    supportedChainIds: [1, 4, 137, 80001],
hey @lupotto,
why not use the keys in `network` here? like:
```
supportedChainIds: Object.keys(network),
```

2022-08-18 12:15 UTC, lupotto commented on pkg/examples/react/src/pages/index.tsx
> +    supportedChainIds: [1, 4, 137, 80001],
yep good point! Thanks daniel!

2022-08-22 11:39 UTC, DeanVanNiekerk approved these changes

2022-08-22 11:39 UTC, merged